# Generated by Django 4.1.13 on 2025-09-29 11:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='VAT % for this product', max_digits=4),
        ),
    ]
