# Generated by Django 4.1.13 on 2025-09-29 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_vat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='VAT %', max_digits=4),
        ),
    ]
